index.html, style.css
https://github.com/Virtual4087/Tree2Hope/assets/80113495/ff7b829b-3c32-4556-8654-6108b60d8b8c
=> Added smooth scrolling to footer on clicking CONTACT

index.html, style.css
=> Update style.css for Gapping

index.html, style.css
fixed : #13 
I have solved the issue #13 .
this is some of the screenshot after it is  redesigned .
Please Provide some feedback and hope You close this isssue soon
=> design :  Footer redesign done 

README.md
Hi @Virtual4087 I Have Added extra info to the Readme file as well as added a contribution list and a short description of the rules and what is expected in the process of contributing to this Project.
Closes #20 
If you could please mark this as completed for Hacktober contribution that would be great! Thank you so much.
=> Closes #20

assets/css/style.css, index.html
#22 Add responsiveness (Solved) 
The given projects is fully Responsive which can work on different devices of different sizes 
and the Menu bar is also added for the responsiveness
=> issueSolved

CONTRIBUTING.md
Added a CONTRIBUTING.md file with all the necessary guidelines required to contribute to this repository.
=> feat:" Add CONTRIBUTING.md"

README.md
Clicking on the profile pictures takes the viewer to the profile of the contributor
=> Add links to contributors

assets/css/style.css, index.html
Change footer view impressive by align social media icon to bottom and copyright section to center
=> Social media icon

README.md
=> Added all the contributors in readme file

index.html
=> Add links to social media icons

.all-contributorsrc, README.md
This PR resolves the issue #45 
Kindly review the PR and merge it, under "hacktoberfest-accepted" label ! 😀
=> docs: added contributors bot

.all-contributorsrc, README.md
Reverts Virtual4087/Tree2Hope#52
=> Revert "docs: added contributors bot"

index.html
Fixes #50 
Edit: I added spacing in between the get involved and events sections.
=> Added bootstrap and added spacing where required

assets/css/style.css
Modified the text color for the text in options under get_involved section.
=> Improved the style of text in get_involved section , Fixes : #51

assets/css/style.css, index.html
**Description**
Added a popup on button click and dropped the background down, matched the buttons and animations a bit. Added a close button inside
#40 
https://github.com/Virtual4087/Tree2Hope/assets/24473439/b84a66ff-9a33-4bdd-9e88-59b86e28a71d
=> Activate donate now button

index.html
#58 
Remove unnecessary text from top left
=> #58 Remove the irrelevant text from top left

assets/css/style.css, index.html
#61 
https://github.com/Virtual4087/Tree2Hope/assets/134940879/1025c5c6-e7b1-4af4-bd7d-55938d804636
**I hope this will be considered under Hacktoberfest 2023.**
=> The popup is styled now and it is added at the required places

assets/css/responsiveness.css
=> Logo size changed for mobile devices

assets/css/style.css
@Virtual4087 
Hey there, I have made the required changes and I am uploading two previews showcasing two different spacing styles. I have created this pull request applying the effects showcased in Preview-1. If you like Preview-2 or something other than these two, then tell me and I will implement it.
From:
To:
Preview-1:
Preview-2:
=> Improved the spacing between the links in the footer , Fixes : #65

.github/workflows/greetings.yml
=> Implement automatic commenting when an issue or pr is opened

about.html, index.html
=> github icon on footer

assets/css/style.css
=> fix:no hover for social media icons

about.html, assets/css/style.css
Hey shovit, did some changes in about page , let me know if anything more needs to be done, this will be my first pr for hacktoberfest!
=> :sparkles:[feat][added background to the image and context in about Us ]

about.html, index.html
=> Fixed "Donate Us" button popup in the Navbar

about.html, assets/css/responsiveness.css, assets/css/style.css
- Added glass effect 
- Improved responsiveness
- Changed the font color to improve readability
- Checked the visuals on Microsoft Edge and Google Chrome
=> Added glass morphism and improved the styling of the About page

about.html, assets/css/responsiveness.css, assets/css/style.css
In reply to suggestion in pr #113:
>The current "About Us" section's text content is not very appealing. If you can you can make it more minimalistic.
- More uniform and less colorful text
- Smaller font size
- Text left justified
- Less padding on mobile
- Poppins for the header
=> Minimalistic About Us text content

about.html
While in the about us page if we wanted to go to the dontate page it was not redirecting us there
and i fixed the same please review and let me know if there are any changes required
=> fixed the redirection issue

assets/css/style.css
1. The position of the nav bar along with its elements has been fixed at the top of the webpage. 
2. A translucent background for the nav bar to enhance visibility has been added.
=> fix the position of the nav bar

assets/css/style.css, index.html
1. The logo had a cursor pointer showing when hovered on it, but did nothing when clicked. Added code to take you back to the home page when you click on logo.
2. The social media icons in the footer showed cursor pointers but did not redirect to the respective pages when clicked. Fixed css to make only the links clickable.
=> Fix minor bugs

assets/css/style.css, index.html
- Implemented dynamic navbar color change on scroll. The navbar is now transparent on the cover page and transitions to a dark background when scrolling to the "WHERE WE PLANT" section.
- Updated JavaScript to target the correct section (.locations.section.mt-5) and handle the scroll event accordingly.
- Added error handling to ensure the navbar and section elements exist before applying the changes.
=> Added Navbar Scroll effect by modifying CSS and JS.

assets/css/style.css
changes made with resolved merge conflicts
=> footer visibility changes

assets/css/style.css, index.html
Reverts Virtual4087/Tree2Hope#131
=> Revert "Added Navbar Scroll effect by modifying CSS and JS."

assets/css/style.css, index.html
The navbar should only appear after the user scrolls past the cover page and reaches "Where we plant" section. The dark background of the nav bar should also be added only then. Otherwise the Navbar should be where it is without the dark background.
Hello @Virtual4087 I have fixed the above issue ,you may review it and merge to main branch.
=> Added scroll effect for navbar

about.html, assets/css/responsiveness.css, assets/css/style.css, index.html
**Issue**: The burger menu was implemented but was not functional, and the responsiveness of the website needed improvement.
**Changes Made**:
- Implemented functionality for the burger menu, allowing it to toggle visibility of the navigation items.
https://github.com/user-attachments/assets/21be1c01-5aff-42f2-929a-76c1809bd2bf
- Enhanced the website's responsiveness to ensure a seamless user experience across different screen sizes.
https://github.com/user-attachments/assets/966464e6-f443-43fe-a5cf-c19caa8bad79
**Impact**: These changes improve the usability of the navigation menu, making it accessible on smaller screens and ensuring that all navbar items are displayed correctly.
=> Make burger menu functional and improve website responsiveness

assets/css/style.css
=> Fixed Navbar overflowing

assets/css/style.css, index.html, scripts/index.js
https://github.com/user-attachments/assets/34009323-aed1-47f4-a0be-edb94ec5e07f
=> added a scroll to top button

about.html
The following changes have been made:
Visibility: The "Events" button is now consistently visible, allowing users to access the events page from any section of the website.
Functionality: The button has been made functional, redirecting users to the events page when clicked.
=> made event button visible

assets/css/style.css
All the previous sections have hover effect except this , so i added some hover effect on this section.
=> Added hover effect  to OUR GOALS

about.html, assets/css/style.css, index.html
#165 Resolved
- Made Hamburger Clickable
- About Us page was missing menu bar in small screen sizes, so added that.
- Some Contact Us links were missing href, added that
https://github.com/user-attachments/assets/21f4d12f-d798-4397-8bc8-b27fccf21ccc
=> Hamburger Clickable

about.html, assets/css/style.css, index.html, scripts/index.js
Uploading Screen Recording 2024-10-20 210139.mp4…
This PR adds AOS (Animate On Scroll) animations to enhance the visual appeal of elements as users scroll through the site. It also introduces a preloader to improve the initial loading experience, ensuring smooth transitions. The animations and preloader are lightweight and configured for optimal performance. These changes improve user engagement and overall aesthetics.
I would be grateful if you could review and accept my PR. Thank you for considering these enhancements.
=> AOS animation added, preloader added, Bug Fixes
